version: "2"
services:
  base:
    image: mysong/ai_django_webservice:base
    ports:
      - "8080:8080"

  app1:
    image: mysong/ai_django_webservice:app1
    ports:
      - "8005:8000"
    depends_on:
      - base
    volumes_from:
      - base

  app2:
    image: mysong/ai_django_webservice:app2
    ports:
      - "8001:8001"
    depends_on:
      - base
    volumes_from:
      - base


