# Generated by Django 2.0.5 on 2020-03-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(max_length=255),
        ),
    ]
